AWSTemplateFormatVersion: "2010-09-09"
Description: Template to deploy an IAM Role to deploy this app.
Resources:
  DeploymentRole:
    Type: "AWS::IAM::Role"
    Properties: 
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - cloudformation.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Description: IAM Role that should have only the required access to deploy this application.
      Policies:
        - PolicyName: root # TODO: This will need to be paired back. Just want to check that it works.
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: '*'
                Resource: '*'

